apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: elk 
  namespace: elk
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/MalekFarhani/ELK-filebeat