apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elk
spec:
  interval: 1m
  chart:
    spec:
      chart: ./kibana
      sourceRef:
        kind: GitRepository
        name: elk
        namespace: elk